{{- if and .Values.secret.enabled .Values.secret.data -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deployguard-runtime.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "deployguard-runtime.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secret.data | nindent 2 }}
{{- end }}
