{{- if and .Values.tetragon.enabled .Values.tetragon.tracingPolicy.enabled }}
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: {{ include "deployguard-runtime.fullname" . }}-policy
  labels:
    {{- include "deployguard-runtime.labels" . | nindent 4 }}
spec:
  kprobes:
  - call: "__x64_sys_openat"
    syscall: true
    args:
    - index: 1
      type: "string"
    selectors:
    - matchArgs:
      - index: 1
        operator: "Prefix"
        values:
        - "/var/run/secrets/kubernetes.io/serviceaccount"
        - "/proc/1"
        - "/etc/shadow"
        - "/etc/kubernetes"
        - "/var/lib/kubelet"
  - call: "tcp_connect"
    syscall: false
    args:
    - index: 0
      type: "sock"
  - call: "__x64_sys_execve"
    syscall: true
    args:
    - index: 0
      type: "string"
    selectors:
    - matchArgs:
      - index: 0
        operator: "Postfix"
        values:
        - "/curl"
        - "/nmap"
        - "/nsenter"
        - "/bash"
        - "/sh"
{{- end }}
