apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: detect-sa-token-access
spec:
  kprobes:
  - call: "sys_openat"
    syscall: true
    args:
    - index: 1
      type: "string"
    selectors:
    - matchArgs:
      - index: 1
        operator: "Prefix"
        values:
        - "/var/run/secrets/kubernetes.io/serviceaccount"
      - index: 1
        operator: "Prefix"
        values:
        - "/proc/1"
        - "/etc/shadow"
        - "/etc/kubernetes"
        - "/var/lib/kubelet"