name: Build and Push Runtime Images

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-2
  AWS_ACCOUNT_ID: "189060532132"
  ECR_REPOSITORY_SCANNER: deployguard-runtime-scanner
  ECR_REPOSITORY_API: deployguard-runtime-api

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          role-to-assume: arn:aws:iam::189060532132:role/deployguard-runtime-ecr-push-policy
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Prepare image tags
        id: prep
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          BUILD_TIME=$(TZ=Asia/Seoul date +'%Y%m%d-%H%M')

          SCANNER_IMAGE_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY_SCANNER}
          API_IMAGE_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY_API}

          echo "short_sha=${SHORT_SHA}" >> $GITHUB_OUTPUT
          echo "build_time=${BUILD_TIME}" >> $GITHUB_OUTPUT
          echo "scanner_image_uri=${SCANNER_IMAGE_URI}" >> $GITHUB_OUTPUT
          echo "api_image_uri=${API_IMAGE_URI}" >> $GITHUB_OUTPUT

      - name: Build scanner image
        run: |
          docker build \
            -t ${{ steps.prep.outputs.scanner_image_uri }}:latest \
            -t ${{ steps.prep.outputs.scanner_image_uri }}:sha-${{ steps.prep.outputs.short_sha }} \
            -t ${{ steps.prep.outputs.scanner_image_uri }}:main-${{ steps.prep.outputs.build_time }} \
            -f Dockerfile .

      - name: Push scanner image
        run: |
          docker push ${{ steps.prep.outputs.scanner_image_uri }}:latest
          docker push ${{ steps.prep.outputs.scanner_image_uri }}:sha-${{ steps.prep.outputs.short_sha }}
          docker push ${{ steps.prep.outputs.scanner_image_uri }}:main-${{ steps.prep.outputs.build_time }}

      - name: Build runtime api image
        run: |
          docker build \
            -t ${{ steps.prep.outputs.api_image_uri }}:latest \
            -t ${{ steps.prep.outputs.api_image_uri }}:sha-${{ steps.prep.outputs.short_sha }} \
            -t ${{ steps.prep.outputs.api_image_uri }}:main-${{ steps.prep.outputs.build_time }} \
            -f runtime_api/Dockerfile ./runtime_api

      - name: Push runtime api image
        run: |
          docker push ${{ steps.prep.outputs.api_image_uri }}:latest
          docker push ${{ steps.prep.outputs.api_image_uri }}:sha-${{ steps.prep.outputs.short_sha }}
          docker push ${{ steps.prep.outputs.api_image_uri }}:main-${{ steps.prep.outputs.build_time }}